-- Seed data for initial development

-- ============================================
-- SITE INFORMATION SEED DATA
-- ============================================
INSERT INTO site_info (key, value_vi, value_en, value_zh, value_plain) VALUES
('company_name', 'CÔNG TY CỔ PHẦN TƯ VẤN THIẾT KẾ XÂY DỰNG HDG', 'HDG Construction Design Consulting Joint Stock Company', 'HDG建筑设计咨询股份公司', NULL),
('company_abbreviation', 'HDG CONSTRUCTION DESIGN CONSULTING JSC', 'HDG CONSTRUCTION DESIGN CONSULTING JSC', 'HDG建筑设计咨询股份公司', NULL),
('registered_address', '125/42/27 Bùi Đình Túy, Phường Bình Thạnh, TP. Hồ Chí Minh, Việt Nam', '125/42/27 Bui Dinh Tuy Street, Binh Thanh Ward, Ho Chi Minh City, Vietnam', '越南胡志明市平盛区裴廷推街125/42/27号', NULL),
('office_address', '362 Mai Chí Thọ, An Phú, TP. Hồ Chí Minh, Việt Nam', '362 Mai Chi Tho Street, An Phu Ward, Ho Chi Minh City, Vietnam', '越南胡志明市安富区梅志寿街362号', NULL),
('phone', NULL, NULL, NULL, '0931313599'),
('email', NULL, NULL, NULL, 'info@hdgcons.com.vn'),
('website', NULL, NULL, NULL, 'www.hdgcons.com.vn'),
('working_hours', 'Thứ 2 - Thứ 6: 8:00 - 17:30', 'Mon - Fri: 8:00 - 17:30', '周一至周五: 8:00 - 17:30', NULL),
('legal_representative', 'Hoàng Đình Cung', 'Mr. Hoang Dinh Cung', '黄廷聪先生', NULL),
('company_profile_url', NULL, NULL, NULL, '/documents/hdg-company-profile.pdf')
ON CONFLICT (key) DO UPDATE SET
    value_vi = EXCLUDED.value_vi,
    value_en = EXCLUDED.value_en,
    value_zh = EXCLUDED.value_zh,
    value_plain = EXCLUDED.value_plain,
    updated_at = NOW();

-- ============================================
-- SERVICES SEED DATA
-- ============================================
INSERT INTO services (slug, name_vi, name_en, name_zh, description_vi, description_en, description_zh, features_vi, features_en, features_zh, icon, order_index, active)
VALUES
(
    'design-consultancy',
    'Tư vấn thiết kế',
    'Design Consultancy',
    '设计咨询',
    'Cung cấp giải pháp thiết kế tối ưu cho mọi loại công trình từ dân dụng, công nghiệp đến hạ tầng',
    'Providing optimal design solutions for all types of buildings from civil, industrial to infrastructure',
    '为各类建筑提供最优设计解决方案，从民用、工业到基础设施',
    ARRAY['Quy hoạch tổng thể', 'Thiết kế khái niệm', 'Tư vấn pháp lý và giấy phép', 'Đánh giá tính khả thi', 'Thiết kế cảnh quan'],
    ARRAY['Master Planning', 'Concept Design', 'Legal and Permit Consultation', 'Feasibility Assessment', 'Landscape Design'],
    ARRAY['总体规划', '概念设计', '法律和许可咨询', '可行性评估', '景观设计'],
    'compass',
    1,
    true
),
(
    'engineering-design',
    'Thiết kế kỹ thuật',
    'Engineering Design',
    '工程设计',
    'Thiết kế chuyên sâu về Kiến trúc, Kết cấu và hệ thống MEP với độ chính xác cao',
    'In-depth design for Architecture, Structure, and MEP systems with high precision',
    '高精度的建筑、结构和MEP系统深度设计',
    ARRAY['Thiết kế kiến trúc chi tiết', 'Thiết kế kết cấu', 'Thiết kế hệ thống M&E', 'Thiết kế PCCC', 'Bản vẽ thi công'],
    ARRAY['Detailed Architectural Design', 'Structural Design', 'M&E System Design', 'Fire Protection Design', 'Construction Drawings'],
    ARRAY['详细建筑设计', '结构设计', 'M&E系统设计', '消防设计', '施工图'],
    'pen-tool',
    2,
    true
),
(
    'integrated-solutions',
    'Giải pháp tổng thể',
    'Integrated Solutions',
    '综合解决方案',
    'Cung cấp giải pháp toàn diện từ giai đoạn ý tưởng đến hoàn thiện và nghiệm thu',
    'Providing comprehensive solutions from concept to completion and handover',
    '从概念阶段到项目完成和移交提供全面解决方案',
    ARRAY['Quản lý dự án toàn diện', 'Giám sát thi công', 'Kiểm soát chất lượng', 'Nghiệm thu và bàn giao', 'Hỗ trợ vận hành'],
    ARRAY['Comprehensive Project Management', 'Construction Supervision', 'Quality Control', 'Acceptance and Handover', 'Operation Support'],
    ARRAY['综合项目管理', '施工监理', '质量控制', '验收和移交', '运营支持'],
    'layers',
    3,
    true
)
ON CONFLICT (slug) DO UPDATE SET
    name_vi = EXCLUDED.name_vi,
    name_en = EXCLUDED.name_en,
    name_zh = EXCLUDED.name_zh,
    description_vi = EXCLUDED.description_vi,
    description_en = EXCLUDED.description_en,
    description_zh = EXCLUDED.description_zh,
    features_vi = EXCLUDED.features_vi,
    features_en = EXCLUDED.features_en,
    features_zh = EXCLUDED.features_zh,
    icon = EXCLUDED.icon,
    order_index = EXCLUDED.order_index,
    active = EXCLUDED.active;

-- Insert project data (based on HDG project portfolio from business-projects.md)
-- All 36 projects from mock-data.ts
INSERT INTO projects (
    slug, title_vi, title_en, title_zh, category, services, location, scale, year, client,
    summary_vi, summary_en, summary_zh, content_vi, content_en, content_zh,
    cover_image, gallery, featured, published, order_index
) VALUES
-- TRACODI GROUP PROJECTS (2024-Present)
(
    'r-pac-factory',
    'Nhà máy R-PAC',
    'R-PAC Factory',
    'R-PAC工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Vietnam',
    'Industrial factory complex',
    2024,
    'Tracodi Group / ADB',
    'Dự án nhà máy công nghiệp hiện đại với thiết kế tối ưu hóa quy trình sản xuất',
    'Modern industrial factory with optimized production process design',
    '现代化工业工厂，优化生产流程设计',
    'Nhà máy R-PAC được thiết kế với công nghệ tiên tiến, tập trung vào hiệu quả sản xuất và bền vững môi trường. Dự án áp dụng các tiêu chuẩn quốc tế về an toàn lao động và quản lý chất lượng.',
    'R-PAC Factory is designed with cutting-edge technology, focusing on production efficiency and environmental sustainability. The project applies international standards for occupational safety and quality management.',
    'R-PAC工厂采用尖端技术设计，注重生产效率和环境可持续性。项目采用国际职业安全和质量管理标准。',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    true,
    true,
    1
),
(
    'hue-dormitory',
    'Ký túc xá Huế',
    'Hue Dormitory',
    '顺化宿舍',
    'commercial',
    ARRAY['design', 'engineering', 'integrated'],
    'Hue, Vietnam',
    'Student dormitory complex',
    2024,
    'Tracodi Group / ADB',
    'Khu ký túc xá sinh viên hiện đại với đầy đủ tiện nghi và không gian sống thoải mái',
    'Modern student dormitory with full amenities and comfortable living spaces',
    '现代化学生宿舍，设施齐全，居住空间舒适',
    'Ký túc xá Huế là dự án nhà ở sinh viên quy mô lớn, được thiết kế với tiêu chí tạo môi trường học tập và sinh hoạt tối ưu. Công trình tích hợp các không gian học tập chung, khu vực thể thao và các tiện ích hiện đại.',
    'Hue Dormitory is a large-scale student housing project designed to create optimal learning and living environments. The building integrates shared study spaces, sports areas, and modern amenities.',
    '顺化宿舍是一个大型学生住房项目，旨在创造最佳的学习和生活环境。建筑整合了共享学习空间、体育区域和现代化设施。',
    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop'],
    true,
    true,
    2
),
(
    'bestmix-ha-nam',
    'Nhà máy Bestmix Hà Nam',
    'Bestmix Ha Nam Factory',
    'Bestmix河南工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Ha Nam, Vietnam',
    'Manufacturing facility',
    2024,
    'Tracodi Group / ADB',
    'Nhà máy sản xuất thức ăn chăn nuôi với công nghệ hiện đại và quy trình tự động hóa',
    'Animal feed manufacturing plant with modern technology and automated processes',
    '采用现代技术和自动化流程的动物饲料生产厂',
    'Bestmix Hà Nam là nhà máy sản xuất thức ăn chăn nuôi công nghệ cao, được trang bị hệ thống tự động hóa tiên tiến. Thiết kế nhà máy tuân thủ các tiêu chuẩn an toàn thực phẩm và bảo vệ môi trường nghiêm ngặt.',
    'Bestmix Ha Nam is a high-tech animal feed production facility equipped with advanced automation systems. The factory design complies with strict food safety and environmental protection standards.',
    'Bestmix河南是一家高科技动物饲料生产设施，配备先进的自动化系统。工厂设计符合严格的食品安全和环境保护标准。',
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    3
),
(
    'vn-apparel',
    'Nhà máy VN Apparel',
    'VN Apparel Factory',
    'VN Apparel工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Vietnam',
    'Textile manufacturing facility',
    2024,
    'Tracodi Group / ADB',
    'Nhà máy may mặc xuất khẩu với hệ thống sản xuất hiện đại và thân thiện môi trường',
    'Export garment factory with modern production systems and eco-friendly design',
    '出口服装厂，采用现代化生产系统和环保设计',
    'VN Apparel là nhà máy may mặc xuất khẩu được thiết kế theo tiêu chuẩn quốc tế, với hệ thống chiếu sáng tự nhiên tối ưu và điều hòa không khí tiên tiến. Công trình đáp ứng các yêu cầu khắt khe của các thương hiệu thời trang toàn cầu.',
    'VN Apparel is an export garment factory designed to international standards, with optimized natural lighting and advanced air conditioning systems. The facility meets stringent requirements of global fashion brands.',
    'VN Apparel是一家按国际标准设计的出口服装厂，具有优化的自然采光和先进的空调系统。该设施满足全球时尚品牌的严格要求。',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop'],
    false,
    true,
    4
),

-- TUNG FENG VIETNAM PROJECTS (2022-2024)
(
    'sgsu-model-house',
    'Nhà mẫu SGSU',
    'SGSU Model House',
    'SGSU样板房',
    'residential',
    ARRAY['design', 'engineering'],
    'Ho Chi Minh City',
    'Model house showroom',
    2023,
    'Tung Feng Vietnam',
    'Nhà mẫu sang trọng thể hiện đẳng cấp thiết kế và chất lượng xây dựng cao cấp',
    'Luxurious model house showcasing premium design and construction quality',
    '豪华样板房，展示高端设计和建筑质量',
    'Nhà mẫu SGSU là công trình trưng bày tiêu chuẩn thiết kế và thi công của dự án bất động sản cao cấp. Mỗi chi tiết được chăm chút tỉ mỉ, từ vật liệu nội thất đến hệ thống cơ điện thông minh.',
    'SGSU Model House is a showcase of design and construction standards for premium real estate projects. Every detail is meticulously crafted, from interior materials to smart MEP systems.',
    'SGSU样板房是高端房地产项目设计和施工标准的展示。从室内材料到智能机电系统，每个细节都精心打造。',
    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop'],
    false,
    true,
    5
),
(
    'villa-complex',
    'Khu biệt thự cao cấp',
    'Luxury Villa Complex',
    '豪华别墅区',
    'residential',
    ARRAY['design', 'engineering', 'integrated'],
    'Ho Chi Minh City',
    'Luxury villa community',
    2023,
    'Tung Feng Vietnam',
    'Khu biệt thự đẳng cấp với thiết kế độc đáo và cảnh quan xanh mát',
    'Premium villa community with unique design and lush green landscapes',
    '高端别墅社区，独特设计，绿意盎然',
    'Khu biệt thự cao cấp được quy hoạch với mật độ xây dựng thấp, tối đa hóa không gian xanh và sự riêng tư cho cư dân. Mỗi căn biệt thự được thiết kế với phong cách kiến trúc độc đáo, hài hòa với thiên nhiên.',
    'The luxury villa complex is planned with low building density, maximizing green space and privacy for residents. Each villa features unique architectural style harmonized with nature.',
    '豪华别墅区规划建筑密度低，最大化绿化空间和居民隐私。每栋别墅都采用独特的建筑风格，与自然和谐统一。',
    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop'],
    true,
    true,
    6
),
(
    'chateau-project',
    'Dự án Chateau',
    'Chateau Project',
    '城堡项目',
    'residential',
    ARRAY['design', 'engineering'],
    'Ho Chi Minh City',
    'High-end residential development',
    2022,
    'Tung Feng Vietnam',
    'Dự án nhà ở phong cách Pháp với kiến trúc cổ điển sang trọng',
    'French-style residential project with elegant classical architecture',
    '法式住宅项目，优雅的古典建筑',
    'Chateau là dự án nhà ở mang đậm phong cách kiến trúc Pháp cổ điển, với các chi tiết trang trí tinh xảo và vật liệu cao cấp. Dự án mang đến không gian sống đẳng cấp châu Âu giữa lòng thành phố.',
    'Chateau is a residential project featuring classic French architecture with exquisite decorative details and premium materials. The project brings European-class living space to the heart of the city.',
    '城堡是一个具有经典法式建筑风格的住宅项目，装饰细节精美，材料高档。该项目将欧洲级生活空间带到城市中心。',
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop'],
    false,
    true,
    7
),

-- PURE VN PROJECTS (2020-2022)
(
    'the-song-apartment',
    'The Song Apartment',
    'The Song Apartment',
    'The Song公寓',
    'residential',
    ARRAY['design', 'engineering', 'integrated'],
    'Vung Tau',
    'Luxury residential, 30 floors',
    2021,
    'Pure VN',
    'Căn hộ cao cấp ven biển với tầm nhìn tuyệt đẹp ra Vịnh Vũng Tàu',
    'Luxury beachfront apartments with stunning views of Vung Tau Bay',
    '海滨豪华公寓，俯瞰头顿湾美景',
    'The Song Apartment là dự án căn hộ cao cấp tại Vũng Tàu, sở hữu vị trí đắc địa ven biển với tầm nhìn ra biển tuyệt đẹp. Thiết kế hiện đại tối ưu hóa ánh sáng tự nhiên và gió biển, mang đến trải nghiệm nghỉ dưỡng ngay trong căn hộ của bạn.',
    'The Song Apartment is a luxury residential project in Vung Tau, featuring prime beachfront location with stunning ocean views. Modern design optimizes natural light and sea breeze, bringing a resort experience right to your home.',
    'The Song公寓是头顿的高端住宅项目，拥有优越的海滨位置和壮丽的海景。现代设计最大化自然采光和海风，为您的家带来度假体验。',
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop'],
    false,
    true,
    8
),
(
    'wonder-sea-office',
    'Tòa nhà văn phòng Wonder Sea',
    'Wonder Sea Office Building',
    'Wonder Sea办公楼',
    'commercial',
    ARRAY['design', 'engineering'],
    'Ho Chi Minh City',
    'Office building, 15 floors',
    2021,
    'Pure VN',
    'Tòa nhà văn phòng hạng A với thiết kế xanh và công nghệ tiết kiệm năng lượng',
    'Grade A office building with green design and energy-saving technology',
    '甲级写字楼，绿色设计，节能技术',
    'Wonder Sea Office là tòa nhà văn phòng hạng A tại TP.HCM, được thiết kế theo tiêu chuẩn xanh với hệ thống HVAC tiên tiến và tối ưu năng lượng. Không gian làm việc linh hoạt đáp ứng nhu cầu đa dạng của doanh nghiệp hiện đại.',
    'Wonder Sea Office is a Grade A office building in HCMC, designed to green standards with advanced HVAC systems and energy optimization. Flexible workspace meets diverse needs of modern businesses.',
    'Wonder Sea办公楼是胡志明市的甲级写字楼，按绿色标准设计，配备先进的暖通空调系统和节能优化。灵活的工作空间满足现代企业的多样化需求。',
    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop'],
    false,
    true,
    9
),
(
    'iml-factory',
    'Nhà máy IML',
    'IML Factory',
    'IML工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Manufacturing facility, 20,000 sqm',
    2021,
    'Pure VN',
    'Nhà máy sản xuất công nghệ cao với hệ thống tự động hóa tiên tiến',
    'High-tech manufacturing facility with advanced automation systems',
    '高科技制造设施，配备先进的自动化系统',
    'Nhà máy IML được thiết kế với công nghệ sản xuất tiên tiến, hệ thống kiểm soát chất lượng nghiêm ngặt và môi trường làm việc an toàn. Công trình đáp ứng các tiêu chuẩn quốc tế về sản xuất công nghiệp.',
    'IML Factory is designed with advanced manufacturing technology, strict quality control systems, and safe working environment. The facility meets international standards for industrial manufacturing.',
    'IML工厂采用先进的制造技术设计，严格的质量控制系统和安全的工作环境。该设施符合工业制造的国际标准。',
    'https://images.unsplash.com/photo-1567449303078-57ad995bd329?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1567449303078-57ad995bd329?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop'],
    false,
    true,
    10
),

-- CHI THANH PROJECTS (2018-2020)
(
    'newhope-factory',
    'Nhà máy Newhope VN',
    'Newhope VN Factory',
    '新希望越南工厂',
    'industrial',
    ARRAY['design', 'engineering', 'integrated'],
    'Dong Nai',
    'Animal feed factory, 35,000 sqm',
    2019,
    'Chi Thanh / Newhope VN',
    'Nhà máy thức ăn chăn nuôi quy mô lớn với công nghệ sản xuất tiên tiến',
    'Large-scale animal feed factory with advanced production technology',
    '大型动物饲料厂，采用先进的生产技术',
    'Newhope VN là nhà máy sản xuất thức ăn chăn nuôi hàng đầu, được trang bị dây chuyền sản xuất tự động hóa cao. Thiết kế nhà máy đảm bảo an toàn thực phẩm, kiểm soát môi trường và hiệu quả năng lượng.',
    'Newhope VN is a leading animal feed production facility equipped with highly automated production lines. Factory design ensures food safety, environmental control, and energy efficiency.',
    '新希望越南是领先的动物饲料生产设施，配备高度自动化的生产线。工厂设计确保食品安全、环境控制和能源效率。',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    11
),
(
    'nhat-pham-food',
    'Nhà máy Nhat Pham Food',
    'Nhat Pham Food Factory',
    'Nhat Pham食品厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Food processing factory, 15,000 sqm',
    2019,
    'Chi Thanh / Nhat Pham Food',
    'Nhà máy chế biến thực phẩm đạt chuẩn vệ sinh an toàn thực phẩm quốc tế',
    'Food processing factory meeting international food safety standards',
    '符合国际食品安全标准的食品加工厂',
    'Nhà máy Nhat Pham Food được thiết kế theo tiêu chuẩn HACCP và ISO 22000, với hệ thống phòng sạch và kiểm soát nhiệt độ nghiêm ngặt. Công trình đảm bảo chất lượng sản phẩm từ nguyên liệu đầu vào đến thành phẩm.',
    'Nhat Pham Food Factory is designed to HACCP and ISO 22000 standards, with clean room systems and strict temperature control. The facility ensures product quality from raw materials to finished goods.',
    'Nhat Pham食品厂按HACCP和ISO 22000标准设计，配备洁净室系统和严格的温度控制。该设施确保从原材料到成品的产品质量。',
    'https://images.unsplash.com/photo-1606836576983-8b458e75221d?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1606836576983-8b458e75221d?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1567449303078-57ad995bd329?w=800&h=600&fit=crop'],
    false,
    true,
    12
),
(
    'king-yuan-tong-phase-2',
    'Nhà máy King Yuan Tong - Giai đoạn 2',
    'King Yuan Tong Factory - Phase 2',
    'King Yuan Tong工厂 - 二期',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Factory expansion, 25,000 sqm',
    2020,
    'Chi Thanh / King Yuan Tong',
    'Mở rộng nhà máy sản xuất với công suất tăng gấp đôi',
    'Factory expansion with doubled production capacity',
    '工厂扩建，产能翻倍',
    'King Yuan Tong Phase 2 là dự án mở rộng nhà máy hiện hữu, tăng gấp đôi công suất sản xuất. Thiết kế tích hợp liền mạch với giai đoạn 1, đảm bảo vận hành liên tục và hiệu quả logistics.',
    'King Yuan Tong Phase 2 is an expansion project of the existing factory, doubling production capacity. Design integrates seamlessly with Phase 1, ensuring continuous operation and logistics efficiency.',
    'King Yuan Tong二期是现有工厂的扩建项目，产能翻倍。设计与一期无缝整合，确保持续运营和物流效率。',
    'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    false,
    true,
    13
),

-- SHING MARK HOSPITAL (2017)
(
    'shing-mark-hospital',
    'Bệnh viện Shing Mark',
    'Shing Mark Hospital',
    '盛马医院',
    'commercial',
    ARRAY['design', 'engineering'],
    'Long Binh Tan, Bien Hoa City, Dong Nai',
    'Hospital complex',
    2017,
    'Shing Mark University Medical Hospital Co., Ltd',
    'Bệnh viện đại học y dược hiện đại với trang thiết bị y tế tiên tiến',
    'Modern university medical hospital with advanced medical equipment',
    '现代化大学医院，配备先进的医疗设备',
    'Bệnh viện Shing Mark là cơ sở y tế hiện đại thuộc Công ty TNHH bệnh viện Đại học Y dược Shing Mark, tọa lạc tại Long Bình Tân, TP. Biên Hòa, tỉnh Đồng Nai. Công trình được thiết kế theo tiêu chuẩn bệnh viện quốc tế với hệ thống cơ điện tiên tiến, đáp ứng các yêu cầu khắt khe về vệ sinh y tế và an toàn bệnh nhân.',
    'Shing Mark Hospital is a modern medical facility owned by Shing Mark University Medical Hospital Co., Ltd, located in Long Binh Tan, Bien Hoa City, Dong Nai Province. The building is designed to international hospital standards with advanced MEP systems, meeting strict requirements for medical hygiene and patient safety.',
    '盛马医院是盛马大学医院有限公司拥有的现代化医疗设施，位于同奈省边和市隆平新。该建筑按国际医院标准设计，配备先进的机电系统，满足医疗卫生和患者安全的严格要求。',
    'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=600&fit=crop'],
    false,
    true,
    14
),

-- DINCO PROJECTS (2014-2018)
(
    'phu-an-thanh-office',
    'Tòa nhà văn phòng Phú An Thạnh',
    'Phu An Thanh Office Building',
    '富安成办公楼',
    'commercial',
    ARRAY['design', 'engineering'],
    'Ho Chi Minh City',
    'Office building, 12 floors',
    2017,
    'Dinco',
    'Tòa nhà văn phòng hiện đại tại vị trí đắc địa trung tâm TP.HCM',
    'Modern office building in prime central HCMC location',
    '位于胡志明市中心黄金地段的现代办公楼',
    'Tòa nhà văn phòng Phú An Thạnh tọa lạc tại vị trí đắc địa TP.HCM, với thiết kế hiện đại và hệ thống cơ điện tiên tiến. Không gian văn phòng linh hoạt phục vụ đa dạng nhu cầu kinh doanh từ startup đến doanh nghiệp lớn.',
    'Phu An Thanh Office Building is located in a prime HCMC location, featuring modern design and advanced MEP systems. Flexible office space serves diverse business needs from startups to large enterprises.',
    '富安成办公楼位于胡志明市黄金地段，采用现代设计和先进的机电系统。灵活的办公空间满足从初创企业到大型企业的多样化商务需求。',
    'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop'],
    false,
    true,
    15
),
(
    'heineken-factory',
    'Nhà máy Heineken',
    'Heineken Factory',
    '喜力工厂',
    'industrial',
    ARRAY['engineering', 'integrated'],
    'Binh Duong',
    'Brewery complex, 50,000 sqm',
    2016,
    'Heineken / Dinco',
    'Nhà máy sản xuất bia đẳng cấp thế giới với công nghệ tiên tiến nhất',
    'World-class brewery with state-of-the-art technology',
    '世界级啤酒厂，采用最先进的技术',
    'Nhà máy Heineken tại Bình Dương là cơ sở sản xuất bia hiện đại bậc nhất Đông Nam Á, với công nghệ tiên tiến từ Hà Lan. Công trình đáp ứng tiêu chuẩn quốc tế về an toàn thực phẩm, bảo vệ môi trường và phát triển bền vững.',
    'Heineken Factory in Binh Duong is one of Southeast Asia''s most modern breweries, featuring advanced technology from the Netherlands. The facility meets international standards for food safety, environmental protection, and sustainable development.',
    '位于平阳的喜力工厂是东南亚最现代化的啤酒厂之一，采用荷兰先进技术。该设施符合食品安全、环境保护和可持续发展的国际标准。',
    'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    false,
    true,
    16
),
(
    'fukuvi-factory',
    'Nhà máy Fukuvi',
    'Fukuvi Factory',
    '福井工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Manufacturing facility, 20,000 sqm',
    2015,
    'Fukuvi / Dinco',
    'Nhà máy sản xuất vật liệu xây dựng Nhật Bản với tiêu chuẩn chất lượng cao',
    'Japanese construction materials factory with high quality standards',
    '日本建材厂，高质量标准',
    'Nhà máy Fukuvi được xây dựng theo tiêu chuẩn Nhật Bản nghiêm ngặt, sản xuất các vật liệu xây dựng chất lượng cao. Thiết kế nhà máy tối ưu hóa quy trình sản xuất và đảm bảo môi trường làm việc an toàn.',
    'Fukuvi Factory is built to strict Japanese standards, producing high-quality construction materials. Factory design optimizes production processes and ensures safe working environment.',
    '福井工厂按严格的日本标准建造，生产高质量建筑材料。工厂设计优化生产流程，确保安全的工作环境。',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop'],
    false,
    true,
    17
),

-- SANOFI VIETNAM (2013-2014)
(
    'sanofi-pharmaceutical',
    'Nhà máy dược phẩm ACE Sanofi',
    'ACE Sanofi Pharmaceutical Factory',
    'ACE赛诺菲制药厂',
    'industrial',
    ARRAY['engineering', 'integrated'],
    'Binh Duong',
    'Pharmaceutical factory, 30,000 sqm',
    2014,
    'Sanofi Vietnam',
    'Nhà máy dược phẩm đạt chuẩn GMP quốc tế với hệ thống phòng sạch tiên tiến',
    'Pharmaceutical factory meeting international GMP standards with advanced clean room systems',
    '符合国际GMP标准的制药厂，配备先进的洁净室系统',
    'Nhà máy ACE Sanofi Việt Nam được xây dựng đạt tiêu chuẩn GMP quốc tế với hệ thống phòng sạch hiện đại nhất. Công trình đảm bảo môi trường sản xuất vô trùng, kiểm soát nhiệt độ và độ ẩm chính xác, đáp ứng yêu cầu khắt khe của ngành dược phẩm.',
    'ACE Sanofi Vietnam factory is built to international GMP standards with the most modern clean room systems. The facility ensures sterile production environment with precise temperature and humidity control, meeting stringent pharmaceutical industry requirements.',
    'ACE赛诺菲越南工厂按国际GMP标准建造，配备最现代化的洁净室系统。该设施确保无菌生产环境，精确控制温度和湿度，满足制药行业的严格要求。',
    'https://images.unsplash.com/photo-1563213126-a4273aed2016?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1563213126-a4273aed2016?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=600&fit=crop'],
    false,
    true,
    18
),

-- COFICO PROJECTS (2012-2013)
(
    'lixil-factory',
    'Nhà máy Lixil',
    'Lixil Factory',
    '骊住工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Dong Nai',
    'Manufacturing facility, 40,000 sqm',
    2013,
    'COFICO / Lixil',
    'Nhà máy sản xuất thiết bị vệ sinh cao cấp của Nhật Bản',
    'Premium Japanese sanitary equipment manufacturing facility',
    '日本高端卫浴设备制造厂',
    'Nhà máy Lixil là cơ sở sản xuất thiết bị vệ sinh cao cấp, được thiết kế theo tiêu chuẩn Nhật Bản với dây chuyền sản xuất tự động hóa. Công trình đáp ứng các yêu cầu nghiêm ngặt về chất lượng và môi trường.',
    'Lixil Factory is a premium sanitary equipment production facility designed to Japanese standards with automated production lines. The facility meets stringent quality and environmental requirements.',
    '骊住工厂是按日本标准设计的高端卫浴设备生产设施，配备自动化生产线。该设施满足严格的质量和环境要求。',
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    false,
    true,
    19
),
(
    'vina-glass-phase-3',
    'Nhà máy Vina Glass - Giai đoạn 3',
    'Vina Glass Factory - Phase 3',
    '越南玻璃厂 - 三期',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Factory expansion, 15,000 sqm',
    2013,
    'COFICO / Vina Glass',
    'Mở rộng nhà máy kính với công nghệ sản xuất hiện đại',
    'Glass factory expansion with modern production technology',
    '玻璃厂扩建，采用现代生产技术',
    'Vina Glass Phase 3 là dự án mở rộng nhà máy sản xuất kính, tăng cường năng lực sản xuất và đa dạng hóa sản phẩm. Thiết kế tích hợp công nghệ mới nhất trong ngành kính xây dựng.',
    'Vina Glass Phase 3 is a glass manufacturing expansion project, enhancing production capacity and product diversification. Design integrates latest technology in construction glass industry.',
    '越南玻璃三期是玻璃制造扩建项目，提升产能和产品多样化。设计整合建筑玻璃行业最新技术。',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    20
),
(
    'vina-koyei',
    'Nhà máy Vina Koyei',
    'Vina Koyei Factory',
    '越南Koyei工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Dong Nai',
    'Steel manufacturing, 25,000 sqm',
    2012,
    'COFICO / Vina Koyei',
    'Nhà máy sản xuất thép với công nghệ Nhật Bản',
    'Steel manufacturing plant with Japanese technology',
    '采用日本技术的钢铁制造厂',
    'Nhà máy Vina Koyei chuyên sản xuất các sản phẩm thép chất lượng cao, áp dụng công nghệ và quy trình quản lý của Nhật Bản. Công trình được thiết kế đảm bảo an toàn lao động và bảo vệ môi trường.',
    'Vina Koyei Factory specializes in high-quality steel products, applying Japanese technology and management processes. The facility is designed to ensure occupational safety and environmental protection.',
    '越南Koyei工厂专门生产高质量钢铁产品，采用日本技术和管理流程。该设施的设计确保职业安全和环境保护。',
    'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop'],
    false,
    true,
    21
),
(
    'air-water-factory',
    'Nhà máy Air Water',
    'Air Water Factory',
    'Air Water工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Industrial gas facility, 10,000 sqm',
    2012,
    'COFICO / Air Water',
    'Nhà máy sản xuất khí công nghiệp với tiêu chuẩn an toàn cao nhất',
    'Industrial gas production facility with highest safety standards',
    '工业气体生产设施，最高安全标准',
    'Air Water là nhà máy sản xuất khí công nghiệp được thiết kế với các tiêu chuẩn an toàn nghiêm ngặt nhất. Hệ thống kiểm soát và giám sát tự động đảm bảo vận hành an toàn 24/7.',
    'Air Water is an industrial gas production facility designed with the strictest safety standards. Automated control and monitoring systems ensure safe 24/7 operation.',
    'Air Water是按最严格安全标准设计的工业气体生产设施。自动化控制和监控系统确保24/7安全运行。',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    false,
    true,
    22
),

-- COLGATE PALMOLIVE (2007-2012)
(
    'colgate-palmolive-factory',
    'Nhà máy Colgate Palmolive Mỹ Phước',
    'Colgate Palmolive My Phuoc Factory',
    '高露洁棕榄美福工厂',
    'industrial',
    ARRAY['engineering', 'integrated'],
    'Binh Duong',
    'Factory complex, 40,000 sqm',
    2011,
    'Colgate Palmolive',
    'Nhà máy sản xuất hàng tiêu dùng đẳng cấp quốc tế với dây chuyền tự động hóa',
    'International-class consumer goods factory with automated production lines',
    '国际级日用消费品工厂，自动化生产线',
    'Nhà máy Colgate Palmolive tại Mỹ Phước là cơ sở sản xuất hiện đại với dây chuyền tự động hóa cao, đáp ứng các tiêu chuẩn quốc tế về an toàn, chất lượng và môi trường. Đây là một trong những nhà máy sản xuất hàng tiêu dùng lớn nhất khu vực.',
    'Colgate Palmolive factory in My Phuoc is a modern production facility with highly automated lines, meeting international standards for safety, quality, and environment. This is one of the largest consumer goods factories in the region.',
    '美福的高露洁棕榄工厂是现代化生产设施，采用高度自动化生产线，符合国际安全、质量和环境标准。这是该地区最大的日用消费品工厂之一。',
    'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop'],
    false,
    true,
    23
),

-- CMIT PORT (2010)
(
    'cmit-port',
    'Cảng quốc tế Cái Mép (CMIT)',
    'Cai Mep International Terminal (CMIT)',
    '盖梅国际码头',
    'infrastructure',
    ARRAY['engineering'],
    'Ba Ria - Vung Tau',
    'International container port',
    2010,
    'CMIT',
    'Cảng container nước sâu lớn nhất Việt Nam, cửa ngõ giao thương quốc tế',
    'Vietnam''s largest deep-water container port, gateway for international trade',
    '越南最大的深水集装箱港口，国际贸易门户',
    'Cảng CMIT là một trong những cảng container nước sâu lớn nhất Việt Nam, có khả năng tiếp nhận tàu container siêu lớn lên đến 18,000 TEU. Cảng đóng vai trò quan trọng trong chuỗi logistics quốc tế, kết nối Việt Nam với các tuyến hàng hải toàn cầu.',
    'CMIT Port is one of Vietnam''s largest deep-water container ports, capable of receiving ultra-large container vessels up to 18,000 TEU. The port plays a crucial role in international logistics, connecting Vietnam with global shipping routes.',
    'CMIT港是越南最大的深水集装箱港口之一，能够接收高达18,000 TEU的超大型集装箱船。该港口在国际物流中发挥重要作用，将越南与全球航运线路连接起来。',
    'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800&h=600&fit=crop'],
    false,
    true,
    24
),

-- PEB VIETNAM (2006-2007)
(
    'unilever-factory',
    'Nhà máy Unilever',
    'Unilever Factory',
    '联合利华工厂',
    'industrial',
    ARRAY['design', 'engineering'],
    'Binh Duong',
    'Consumer goods factory, 30,000 sqm',
    2007,
    'PEB Vietnam / Unilever',
    'Nhà máy sản xuất hàng tiêu dùng với kết cấu thép tiền chế hiện đại',
    'Consumer goods factory with modern pre-engineered steel structure',
    '采用现代预制钢结构的日用消费品工厂',
    'Nhà máy Unilever được xây dựng với kết cấu thép tiền chế hiện đại, rút ngắn thời gian thi công và đảm bảo chất lượng cao. Thiết kế nhà máy tối ưu hóa không gian sản xuất và logistics nội bộ.',
    'Unilever Factory is built with modern pre-engineered steel structure, shortening construction time while ensuring high quality. Factory design optimizes production space and internal logistics.',
    '联合利华工厂采用现代预制钢结构建造，缩短施工时间，确保高质量。工厂设计优化生产空间和内部物流。',
    'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    25
),

-- SMEC INFRASTRUCTURE PROJECTS (2004-2006)
(
    'luong-the-tran-bridge',
    'Cầu Lương Thế Trân',
    'Luong The Tran Bridge',
    '梁世陈桥',
    'infrastructure',
    ARRAY['engineering'],
    'Mekong Delta',
    'Bridge construction',
    2005,
    'SMEC',
    'Cầu giao thông quan trọng kết nối vùng Đồng bằng sông Cửu Long',
    'Important transportation bridge connecting the Mekong Delta region',
    '连接湄公河三角洲地区的重要交通桥梁',
    'Cầu Lương Thế Trân là công trình hạ tầng quan trọng, góp phần cải thiện giao thông và phát triển kinh tế vùng Đồng bằng sông Cửu Long. Thiết kế cầu đảm bảo khả năng chịu tải cao và tuổi thọ lâu dài.',
    'Luong The Tran Bridge is an important infrastructure project, contributing to improved transportation and economic development in the Mekong Delta region. Bridge design ensures high load capacity and long service life.',
    '梁世陈桥是重要的基础设施项目，有助于改善湄公河三角洲地区的交通和经济发展。桥梁设计确保高承载能力和长使用寿命。',
    'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=600&fit=crop'],
    false,
    true,
    26
),
(
    'giao-long-port',
    'Cảng Giao Long',
    'Giao Long Port',
    '交龙港',
    'infrastructure',
    ARRAY['engineering'],
    'Ben Tre',
    'River port facility',
    2005,
    'SMEC',
    'Cảng sông phục vụ vận chuyển hàng hóa vùng Đồng bằng sông Cửu Long',
    'River port serving cargo transportation in the Mekong Delta',
    '服务湄公河三角洲货物运输的河港',
    'Cảng Giao Long được xây dựng để phục vụ nhu cầu vận chuyển hàng hóa ngày càng tăng của vùng Đồng bằng sông Cửu Long. Thiết kế cảng đảm bảo khả năng tiếp nhận tàu thuyền đa dạng và vận hành hiệu quả.',
    'Giao Long Port is built to serve the growing cargo transportation needs of the Mekong Delta region. Port design ensures capability to receive diverse vessels and efficient operation.',
    '交龙港的建设是为了满足湄公河三角洲地区日益增长的货物运输需求。港口设计确保能够接收多种船舶并高效运营。',
    'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&h=600&fit=crop'],
    false,
    true,
    27
),

-- HAZAMA VIETNAM PROJECTS (1997-2003)
(
    'wacoal-factory',
    'Nhà máy Wacoal',
    'Wacoal Factory',
    '华歌尔工厂',
    'industrial',
    ARRAY['engineering'],
    'Dong Nai',
    'Textile factory, 20,000 sqm',
    2000,
    'HAZAMA VN / Wacoal',
    'Nhà máy sản xuất đồ lót cao cấp Nhật Bản với tiêu chuẩn chất lượng khắt khe',
    'Premium Japanese lingerie factory with strict quality standards',
    '日本高端内衣厂，严格的质量标准',
    'Nhà máy Wacoal được xây dựng theo tiêu chuẩn Nhật Bản, với môi trường sản xuất sạch và hệ thống kiểm soát chất lượng nghiêm ngặt. Công trình đáp ứng yêu cầu cao về điều kiện làm việc và an toàn lao động.',
    'Wacoal Factory is built to Japanese standards, with clean production environment and strict quality control systems. The facility meets high requirements for working conditions and occupational safety.',
    '华歌尔工厂按日本标准建造，拥有清洁的生产环境和严格的质量控制系统。该设施满足工作条件和职业安全的高要求。',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop'],
    false,
    true,
    28
),
(
    'shimazu-factory',
    'Nhà máy Shimazu',
    'Shimazu Factory',
    '岛津工厂',
    'industrial',
    ARRAY['engineering'],
    'Dong Nai',
    'Electronics factory, 15,000 sqm',
    1999,
    'HAZAMA VN / Shimazu',
    'Nhà máy điện tử Nhật Bản với phòng sạch và kiểm soát môi trường chính xác',
    'Japanese electronics factory with clean room and precise environmental control',
    '日本电子厂，配备洁净室和精确的环境控制',
    'Nhà máy Shimazu chuyên sản xuất các thiết bị điện tử chính xác, yêu cầu môi trường sản xuất kiểm soát nghiêm ngặt. Hệ thống phòng sạch và kiểm soát nhiệt độ, độ ẩm đảm bảo chất lượng sản phẩm cao nhất.',
    'Shimazu Factory specializes in precision electronics manufacturing, requiring strictly controlled production environment. Clean room systems and temperature, humidity control ensure highest product quality.',
    '岛津工厂专门生产精密电子产品，需要严格控制的生产环境。洁净室系统和温湿度控制确保最高的产品质量。',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    29
),
(
    'nec-tokin-factory',
    'Nhà máy NEC/Tokin',
    'NEC/Tokin Factory',
    'NEC/Tokin工厂',
    'industrial',
    ARRAY['engineering'],
    'Dong Nai',
    'Electronics factory, 18,000 sqm',
    1998,
    'HAZAMA VN / NEC/Tokin',
    'Nhà máy sản xuất linh kiện điện tử với công nghệ tiên tiến từ Nhật Bản',
    'Electronic components factory with advanced Japanese technology',
    '采用日本先进技术的电子元件厂',
    'Nhà máy NEC/Tokin sản xuất các linh kiện điện tử chất lượng cao, áp dụng công nghệ và quy trình quản lý tiên tiến của Nhật Bản. Thiết kế nhà máy đảm bảo môi trường sản xuất tối ưu và hiệu quả năng lượng.',
    'NEC/Tokin Factory produces high-quality electronic components, applying advanced Japanese technology and management processes. Factory design ensures optimal production environment and energy efficiency.',
    'NEC/Tokin工厂生产高质量电子元件，采用日本先进技术和管理流程。工厂设计确保最佳生产环境和能源效率。',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop'],
    false,
    true,
    30
),
(
    'ajinomoto-factory',
    'Nhà máy Ajinomoto',
    'Ajinomoto Factory',
    '味之素工厂',
    'industrial',
    ARRAY['engineering'],
    'Dong Nai',
    'Food factory, 25,000 sqm',
    2001,
    'HAZAMA VN / Ajinomoto',
    'Nhà máy thực phẩm Nhật Bản với tiêu chuẩn an toàn vệ sinh thực phẩm cao nhất',
    'Japanese food factory with highest food safety and hygiene standards',
    '日本食品厂，最高的食品安全和卫生标准',
    'Nhà máy Ajinomoto Việt Nam được xây dựng theo tiêu chuẩn Nhật Bản với hệ thống sản xuất hiện đại, đảm bảo chất lượng sản phẩm cao cấp. Công trình áp dụng các tiêu chuẩn an toàn vệ sinh thực phẩm nghiêm ngặt nhất.',
    'Ajinomoto Vietnam factory is built to Japanese standards with modern production systems, ensuring premium product quality. The facility applies the strictest food safety and hygiene standards.',
    '味之素越南工厂按日本标准建造，采用现代化生产系统，确保优质产品质量。该设施采用最严格的食品安全和卫生标准。',
    'https://images.unsplash.com/photo-1567449303078-57ad995bd329?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1567449303078-57ad995bd329?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1606836576983-8b458e75221d?w=800&h=600&fit=crop'],
    false,
    true,
    31
),
(
    'japanese-school',
    'Trường học Nhật Bản',
    'Japanese School',
    '日本学校',
    'commercial',
    ARRAY['design', 'engineering'],
    'Ho Chi Minh City',
    'Educational facility, 8,000 sqm',
    2002,
    'HAZAMA VN',
    'Cơ sở giáo dục đạt chuẩn Nhật Bản với môi trường học tập hiện đại',
    'Japanese-standard educational facility with modern learning environment',
    '符合日本标准的教育设施，现代化学习环境',
    'Trường học Nhật Bản tại TP.HCM được thiết kế theo tiêu chuẩn giáo dục Nhật Bản, với các phòng học hiện đại, không gian thể chất và khu vực sinh hoạt ngoài trời. Công trình tạo môi trường học tập an toàn và thân thiện.',
    'Japanese School in HCMC is designed to Japanese educational standards, with modern classrooms, physical activity spaces, and outdoor living areas. The facility creates a safe and friendly learning environment.',
    '胡志明市的日本学校按日本教育标准设计，配备现代化教室、体育活动空间和户外生活区。该设施创造了安全友好的学习环境。',
    'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&h=600&fit=crop'],
    false,
    true,
    32
),

-- MITSUI CONSTRUCTION (1995-1997)
(
    'bp-petro-factory',
    'Nhà máy dầu nhờn BP-PETRO',
    'BP-PETRO Lubricant Factory',
    'BP-PETRO润滑油厂',
    'industrial',
    ARRAY['engineering'],
    'Binh Duong',
    'Lubricant factory, 15,000 sqm',
    1996,
    'Mitsui Construction / BP-PETRO',
    'Nhà máy sản xuất dầu nhờn và dầu mỡ với tiêu chuẩn an toàn quốc tế',
    'Lubricant and grease production factory with international safety standards',
    '符合国际安全标准的润滑油和润滑脂生产厂',
    'Nhà máy BP-PETRO chuyên sản xuất các sản phẩm dầu nhờn và dầu mỡ chất lượng cao, được thiết kế với các tiêu chuẩn an toàn nghiêm ngặt trong ngành hóa dầu. Hệ thống phòng cháy chữa cháy và kiểm soát môi trường tiên tiến.',
    'BP-PETRO Factory specializes in high-quality lubricant and grease products, designed with strict safety standards in the petrochemical industry. Advanced fire protection and environmental control systems.',
    'BP-PETRO工厂专门生产高质量润滑油和润滑脂产品，按石化行业严格的安全标准设计。配备先进的消防和环境控制系统。',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=600&fit=crop'],
    false,
    true,
    33
),

-- GCC1 (1995)
(
    'mitsubishi-motors-factory',
    'Nhà máy Mitsubishi Motors VN',
    'Mitsubishi Motors VN Factory',
    '三菱汽车越南工厂',
    'industrial',
    ARRAY['engineering'],
    'Binh Duong',
    'Automotive assembly plant, 30,000 sqm',
    1995,
    'GCC1 / Mitsubishi Motors',
    'Nhà máy lắp ráp ô tô với dây chuyền sản xuất hiện đại từ Nhật Bản',
    'Automotive assembly plant with modern Japanese production lines',
    '采用日本现代化生产线的汽车装配厂',
    'Nhà máy Mitsubishi Motors VN là một trong những nhà máy lắp ráp ô tô đầu tiên tại Việt Nam, được trang bị dây chuyền sản xuất hiện đại từ Nhật Bản. Thiết kế nhà máy đảm bảo quy trình sản xuất hiệu quả và chất lượng cao.',
    'Mitsubishi Motors VN Factory is one of the first automotive assembly plants in Vietnam, equipped with modern Japanese production lines. Factory design ensures efficient production processes and high quality.',
    '三菱汽车越南工厂是越南最早的汽车装配厂之一，配备日本现代化生产线。工厂设计确保高效的生产流程和高质量。',
    'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1200&h=800&fit=crop',
    ARRAY['https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop'],
    false,
    true,
    34
)
ON CONFLICT (slug) DO UPDATE SET
    title_vi = EXCLUDED.title_vi,
    title_en = EXCLUDED.title_en,
    title_zh = EXCLUDED.title_zh,
    category = EXCLUDED.category,
    services = EXCLUDED.services,
    location = EXCLUDED.location,
    scale = EXCLUDED.scale,
    year = EXCLUDED.year,
    client = EXCLUDED.client,
    summary_vi = EXCLUDED.summary_vi,
    summary_en = EXCLUDED.summary_en,
    summary_zh = EXCLUDED.summary_zh,
    content_vi = EXCLUDED.content_vi,
    content_en = EXCLUDED.content_en,
    content_zh = EXCLUDED.content_zh,
    cover_image = EXCLUDED.cover_image,
    gallery = EXCLUDED.gallery,
    featured = EXCLUDED.featured,
    published = EXCLUDED.published,
    order_index = EXCLUDED.order_index,
    updated_at = NOW();

-- ============================================
-- TEAM MEMBERS SEED DATA
-- ============================================

INSERT INTO team (
    name, role_vi, role_en, role_zh, bio_vi, bio_en, bio_zh,
    education_vi, education_en, education_zh,
    certifications_vi, certifications_en, certifications_zh,
    photo, order_index, active
) VALUES
-- Design Leads
(
    'Hoàng Đình Cung',
    'Chủ trì thiết kế / Giám sát xây dựng',
    'Design Lead / Construction Supervisor',
    '设计负责人 / 施工监理',
    'Kỹ sư xây dựng với hơn 30 năm kinh nghiệm, chuyên giám sát công tác xây dựng công trình dân dụng, công nghiệp và hạ tầng kỹ thuật. Chứng chỉ hành nghề Hạng I.',
    'Construction engineer with over 30 years of experience, specializing in supervising civil, industrial, and infrastructure construction works. Class I professional license.',
    '拥有30多年经验的建筑工程师，专门从事民用、工业和基础设施建设工程的监理工作。一级执业资格证书。',
    'Đại học Bách Khoa TP. Hồ Chí Minh - Kỹ sư xây dựng',
    'Ho Chi Minh City University of Technology - Construction Engineer',
    '胡志明市理工大学 - 建筑工程师',
    ARRAY['Giám sát công tác xây dựng công trình dân dụng - công nghiệp và hạ tầng kỹ thuật (Hạng I)'],
    ARRAY['Construction Supervision for Civil - Industrial and Infrastructure Works (Class I)'],
    ARRAY['民用-工业及基础设施工程施工监理（一级）'],
    '/images/default-men.png',
    1,
    true
),
(
    'Trần Ngọc Chính',
    'Chủ trì thiết kế / Giám sát xây dựng',
    'Design Lead / Construction Supervisor',
    '设计负责人 / 施工监理',
    'Kỹ sư xây dựng chuyên ngành kỹ thuật công trình với kinh nghiệm sâu rộng trong giám sát xây dựng công trình dân dụng, công nghiệp và hạ tầng. Chứng chỉ hành nghề Hạng I.',
    'Construction engineer specializing in building technology with extensive experience in supervising civil, industrial, and infrastructure construction. Class I professional license.',
    '专门从事建筑技术的建筑工程师，在民用、工业和基础设施建设监理方面拥有丰富经验。一级执业资格证书。',
    'Đại học kỹ thuật - Đại học Quốc gia Tp.Hồ Chí Minh - Kỹ sư xây dựng ngành kỹ thuật công trình',
    'University of Technology - Vietnam National University HCMC - Construction Engineer',
    '胡志明市国家大学技术大学 - 建筑工程师',
    ARRAY['Giám sát công tác xây dựng công trình dân dụng - công nghiệp và hạ tầng kỹ thuật (Hạng I)'],
    ARRAY['Construction Supervision for Civil - Industrial and Infrastructure Works (Class I)'],
    ARRAY['民用-工业及基础设施工程施工监理（一级）'],
    '/images/default-men.png',
    2,
    true
),
-- Architectural Designers
(
    'Lê Xuân Đức',
    'Kiến trúc sư',
    'Architect',
    '建筑师',
    'Kiến trúc sư với chứng chỉ thiết kế kiến trúc công trình và thiết kế đô thị. Chuyên về thiết kế kiến trúc trong đồ án quy hoạch và thiết kế đô thị.',
    'Licensed architect with certifications in building architectural design and urban design. Specializes in architectural design for planning projects and urban design.',
    '持有建筑设计和城市设计资格证书的注册建筑师。专门从事规划项目和城市设计中的建筑设计。',
    'Đại học Kiến trúc Hà Nội - Kiến trúc sư',
    'Hanoi Architectural University - Architect',
    '河内建筑大学 - 建筑师',
    ARRAY['Thiết kế kiến trúc công trình', 'Thiết kế kiến trúc trong đồ án quy hoạch, thiết kế đô thị'],
    ARRAY['Building Architectural Design', 'Architectural Design in Planning Projects, Urban Design'],
    ARRAY['建筑设计', '规划项目和城市设计中的建筑设计'],
    '/images/default-men.png',
    3,
    true
),
(
    'Ngô Phước Quang Thặng',
    'Kiến trúc sư',
    'Architect',
    '建筑师',
    'Kiến trúc sư với chứng chỉ hành nghề thiết kế kiến trúc công trình. Chuyên về thiết kế các công trình cao tầng và tổ hợp đa chức năng.',
    'Licensed architect with building architectural design certification. Specializes in high-rise buildings and mixed-use complexes.',
    '持有建筑设计执业资格证书的注册建筑师。专门从事高层建筑和综合体设计。',
    'Kiến trúc sư',
    'Architect',
    '建筑师',
    ARRAY['Thiết kế kiến trúc công trình'],
    ARRAY['Building Architectural Design'],
    ARRAY['建筑设计'],
    '/images/default-men.png',
    4,
    true
),
-- Structural Designers
(
    'Đặng Hữu Lợi',
    'Kỹ sư kết cấu / Giám sát xây dựng',
    'Structural Engineer / Construction Supervisor',
    '结构工程师 / 施工监理',
    'Thạc sĩ kỹ thuật xây dựng công trình đặc biệt với chứng chỉ Hạng I về giám sát và thiết kế kết cấu. Chuyên về xây dựng dân dụng và công nghiệp.',
    'Master''s degree in special construction engineering with Class I certifications in supervision and structural design. Specializes in civil and industrial construction.',
    '特种建筑工程硕士学位，持有一级监理和结构设计资格证书。专门从事民用和工业建设。',
    'Học Viện kỹ thuật quân sự - Thạc sĩ kỹ thuật xây dựng công trình đặc biệt (Xây dựng dân dụng - công nghiệp)',
    'Military Technical Academy - Master''s in Special Construction Engineering (Civil - Industrial)',
    '军事技术学院 - 特种建筑工程硕士（民用-工业）',
    ARRAY['Giám sát công tác xây dựng công trình dân dụng - công nghiệp và hạ tầng kỹ thuật (Hạng I)', 'Thiết kế kết cấu công trình (Hạng I)'],
    ARRAY['Construction Supervision for Civil - Industrial and Infrastructure Works (Class I)', 'Structural Design (Class I)'],
    ARRAY['民用-工业及基础设施工程施工监理（一级）', '结构设计（一级）'],
    '/images/default-men.png',
    5,
    true
),
(
    'Nguyễn Đình Tuấn',
    'Kỹ sư kết cấu / Giám sát xây dựng',
    'Structural Engineer / Construction Supervisor',
    '结构工程师 / 施工监理',
    'Kỹ sư xây dựng với chứng chỉ Hạng II về thiết kế kết cấu và giám sát công trình dân dụng - công nghiệp. Chuyên về kết cấu thép và bê tông.',
    'Construction engineer with Class II certifications in structural design and civil-industrial construction supervision. Specializes in steel and concrete structures.',
    '建筑工程师，持有二级结构设计和民用-工业建设监理资格证书。专门从事钢结构和混凝土结构。',
    'ĐH Kiến trúc TP.HCM - Kỹ sư xây dựng',
    'Ho Chi Minh City University of Architecture - Construction Engineer',
    '胡志明市建筑大学 - 建筑工程师',
    ARRAY['Thiết kế kết cấu công trình dân dụng - công nghiệp (Hạng II)', 'Giám sát công tác xây dựng công trình dân dụng - công nghiệp (Hạng II)', 'Giám sát công tác xây dựng công trình hạ tầng kỹ thuật (Hạng III)'],
    ARRAY['Structural Design for Civil - Industrial Works (Class II)', 'Construction Supervision for Civil - Industrial Works (Class II)', 'Infrastructure Construction Supervision (Class III)'],
    ARRAY['民用-工业工程结构设计（二级）', '民用-工业工程施工监理（二级）', '基础设施工程施工监理（三级）'],
    '/images/default-men.png',
    6,
    true
),
-- MEPF Designers
(
    'Trương Thanh Hải',
    'Kỹ sư Cơ điện',
    'MEP Engineer',
    '机电工程师',
    'Kỹ sư điện - điện tử với chứng chỉ Hạng I về thiết kế cơ - điện công trình. Chuyên gia thiết kế hệ thống MEP cho các công trình công nghiệp và thương mại.',
    'Electrical-Electronics engineer with Class I certification in MEP design. Expert in MEP system design for industrial and commercial buildings.',
    '电气电子工程师，持有一级机电设计资格证书。工业和商业建筑机电系统设计专家。',
    'Đại học Công Nghệ Sài Gòn - Kỹ sư điện - điện tử',
    'Saigon Technology University - Electrical-Electronics Engineer',
    '西贡理工大学 - 电气电子工程师',
    ARRAY['Thiết kế cơ - điện công trình (Hạng I)'],
    ARRAY['MEP Design (Class I)'],
    ARRAY['机电设计（一级）'],
    '/images/default-men.png',
    7,
    true
),
(
    'Huỳnh Văn Hùng',
    'Kỹ sư Cơ điện / Giám sát lắp đặt',
    'MEP Engineer / Installation Supervisor',
    '机电工程师 / 安装监理',
    'Kỹ sư điện - điện tử với chứng chỉ thiết kế cơ điện Hạng II và giám sát lắp đặt thiết bị điện Hạng III. Chuyên về hệ thống HVAC và điện cho công trình cao tầng.',
    'Electrical-Electronics engineer with Class II MEP design and Class III electrical installation supervision certifications. Specializes in HVAC and electrical systems for high-rise buildings.',
    '电气电子工程师，持有二级机电设计和三级电气安装监理资格证书。专门从事高层建筑的暖通空调和电气系统。',
    'ĐH Công nghệ Sài Gòn - Kỹ sư Điện - điện tử',
    'Saigon Technology University - Electrical-Electronics Engineer',
    '西贡理工大学 - 电气电子工程师',
    ARRAY['Thiết kế cơ - điện công trình dân dụng - công nghiệp (Hạng II)', 'Giám sát công tác lắp đặt thiết bị điện công trình dân dụng - công nghiệp (Hạng III)'],
    ARRAY['MEP Design for Civil - Industrial Works (Class II)', 'Electrical Installation Supervision for Civil - Industrial Works (Class III)'],
    ARRAY['民用-工业工程机电设计（二级）', '民用-工业工程电气安装监理（三级）'],
    '/images/default-men.png',
    8,
    true
),
(
    'Nguyễn Ngọc Tuấn',
    'Kỹ sư Cơ điện / Giám sát lắp đặt',
    'MEP Engineer / Installation Supervisor',
    '机电工程师 / 安装监理',
    'Kỹ sư điện khí hóa và cung cấp điện với chứng chỉ Hạng I về giám sát công tác lắp đặt thiết bị vào công trình.',
    'Electrical engineer specializing in power supply with Class I certification for equipment installation supervision.',
    '电气化和供电工程师，持有一级设备安装监理资格证书。',
    'Đại học Sư phạm kỹ thuật Tp. Hồ Chí Minh - Kỹ sư Điện khí hóa và cung cấp điện',
    'HCMC University of Technology and Education - Electrical Engineer (Power Supply)',
    '胡志明市技术教育大学 - 电气化和供电工程师',
    ARRAY['Giám sát công tác lắp đặt thiết bị vào công trình (Hạng I)'],
    ARRAY['Equipment Installation Supervision (Class I)'],
    ARRAY['设备安装监理（一级）'],
    '/images/default-men.png',
    9,
    true
),
-- Infrastructure Designer
(
    'Lê Xuân Lương',
    'Kỹ sư Hạ tầng / Thiết kế giao thông',
    'Infrastructure Engineer / Transportation Designer',
    '基础设施工程师 / 交通设计师',
    'Kỹ sư xây dựng cầu đường với nhiều chứng chỉ hành nghề Hạng II-III về định giá, thiết kế và giám sát công trình giao thông, hạ tầng kỹ thuật.',
    'Bridge and road construction engineer with multiple Class II-III certifications in valuation, design, and supervision of transportation and infrastructure works.',
    '桥梁道路建设工程师，持有多项二级至三级估价、设计和交通基础设施工程监理资格证书。',
    'Đại học Lạc Hồng - KS XD Cầu đường',
    'Lac Hong University - Bridge & Road Construction Engineer',
    '乐鸿大学 - 桥梁道路建设工程师',
    ARRAY['Định giá xây dựng (Hạng II)', 'Thiết kế xây dựng công trình Giao thông: Đường bộ (Hạng II)', 'Giám sát công tác xây dựng công trình Dân dụng - Công nghiệp - Hạ tầng kỹ thuật và Giao thông (Đường bộ) (Hạng II)', 'Giám sát công tác xây dựng công trình Giao thông: Cầu đường bộ (Hạng III)'],
    ARRAY['Construction Valuation (Class II)', 'Transportation Design: Roads (Class II)', 'Construction Supervision for Civil - Industrial - Infrastructure and Transportation (Roads) (Class II)', 'Transportation Construction Supervision: Road Bridges (Class III)'],
    ARRAY['建设估价（二级）', '交通设计：公路（二级）', '民用-工业-基础设施及交通工程施工监理（公路）（二级）', '交通工程施工监理：公路桥梁（三级）'],
    '/images/default-men.png',
    10,
    true
),
-- Surveying Engineer
(
    'Huỳnh Văn Phụng',
    'Kỹ sư Trắc địa',
    'Surveying Engineer',
    '测量工程师',
    'Kỹ sư Xây dựng Trắc địa và bản đồ với chứng chỉ Hạng II về khảo sát địa hình. Chuyên về khảo sát và đo đạc cho các dự án xây dựng.',
    'Surveying and mapping engineer with Class II topographic survey certification. Specializes in surveying and measurement for construction projects.',
    '测量和制图工程师，持有二级地形测量资格证书。专门从事建设项目的测量和测绘工作。',
    'Đại học Bách Khoa - ĐH Quốc Gia TP.HCM - Kỹ sư Xây dựng Trắc địa và bản đồ',
    'University of Technology - VNU HCMC - Surveying and Mapping Engineer',
    '胡志明市国家大学理工大学 - 测量和制图工程师',
    ARRAY['Khảo sát Địa hình (Hạng II)'],
    ARRAY['Topographic Survey (Class II)'],
    ARRAY['地形测量（二级）'],
    '/images/default-men.png',
    11,
    true
),
-- Project Manager
(
    'Nghiêm Trung Minh',
    'Quản lý dự án',
    'Project Manager',
    '项目经理',
    'Kỹ sư xây dựng cầu đường với chứng chỉ Hạng I về quản lý dự án đầu tư xây dựng công trình dân dụng. Nhiều năm kinh nghiệm điều phối dự án từ thiết kế đến hoàn thiện.',
    'Bridge and road construction engineer with Class I certification in civil construction project management. Years of experience coordinating projects from design to completion.',
    '桥梁道路建设工程师，持有一级民用建设项目管理资格证书。多年项目协调经验，从设计到完工。',
    'Đại học Giao thông vận tải - Kỹ sư xây dựng cầu đường',
    'University of Transport and Communications - Bridge & Road Construction Engineer',
    '交通运输大学 - 桥梁道路建设工程师',
    ARRAY['Quản lý dự án đầu tư xây dựng công trình dân dụng (Hạng I)'],
    ARRAY['Civil Construction Investment Project Management (Class I)'],
    ARRAY['民用建设投资项目管理（一级）'],
    '/images/default-men.png',
    12,
    true
),
-- Estimating Engineers
(
    'Lâm Thị Lệ Thu',
    'Kỹ sư Dự toán',
    'Estimating Engineer',
    '估算工程师',
    'Chuyên gia dự toán và quản lý chi phí dự án, đảm bảo tính chính xác và hiệu quả đầu tư.',
    'Cost estimation and project cost management expert, ensuring accuracy and investment efficiency.',
    '成本估算和项目成本管理专家，确保准确性和投资效率。',
    NULL,
    NULL,
    NULL,
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    '/images/default-women.png',
    13,
    true
),
(
    'Nguyễn Châu Tuấn',
    'Kỹ sư Dự toán',
    'Estimating Engineer',
    '估算工程师',
    'Kỹ sư dự toán với kinh nghiệm trong các dự án xây dựng lớn, chuyên về phân tích giá và đấu thầu.',
    'Estimating engineer with experience in large construction projects, specializing in cost analysis and tendering.',
    '估算工程师，在大型建筑项目中拥有丰富经验，专注于成本分析和招标。',
    NULL,
    NULL,
    NULL,
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    '/images/default-men.png',
    14,
    true
),
-- Chief Accountant
(
    'Nguyễn Thị Ngọc Hà',
    'Kế Toán Trưởng',
    'Chief Accountant',
    '总会计师',
    'Kế toán trưởng với nhiều năm kinh nghiệm quản lý tài chính và kế toán cho các dự án xây dựng.',
    'Chief accountant with years of experience in financial and accounting management for construction projects.',
    '总会计师，在建筑项目的财务和会计管理方面拥有多年经验。',
    NULL,
    NULL,
    NULL,
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    '/images/default-women.png',
    15,
    true
)
ON CONFLICT DO NOTHING;

-- ============================================
-- CLIENTS & PARTNERS SEED DATA
-- ============================================

INSERT INTO clients (name, logo_url, website, category, order_index, active) VALUES
-- Order matches mock-data.ts exactly
('Ajinomoto', '/images/clients/ajinomoto.ico', NULL, 'japanese', 1, true),
('Wacoal', '/images/clients/thumb_wacoal.png', NULL, 'japanese', 2, true),
('Sanofi', '/images/clients/sanofi.webp', NULL, 'multinational', 3, true),
('Colgate Palmolive', '/images/clients/Colgate-Palmolive.webp', NULL, 'multinational', 4, true),
('Heineken', '/images/clients/heineken.webp', NULL, 'multinational', 5, true),
('Shing Mark', '/images/clients/shing-mark.png', NULL, 'construction', 6, true),
('Mitsubishi Motors', '/images/clients/mitsubishi-motors-vietnam-logo.png', NULL, 'multinational', 7, true),
('Bestmix', '/images/clients/bestmix.jpg', NULL, 'multinational', 8, true),
('R-PAC', '/images/clients/r-pac_service.jpg', NULL, 'multinational', 9, true),
('Tribeco', '/images/clients/LOGO-TRIBECO.webp', NULL, 'multinational', 10, true),
('Unilever', '/images/clients/logo-unilever.png', NULL, 'multinational', 11, true),
('Fukuvi', '/images/clients/fukuvi.png', NULL, 'japanese', 12, true),
('KTX Huế', '/images/clients/ktx-hue.png', NULL, 'construction', 13, true),
('Nissey', '/images/clients/nissei.png', NULL, 'japanese', 14, true),
('Air Water', '/images/clients/air-water.png', NULL, 'multinational', 15, true),
('VPIC', '/images/clients/logo-vpic.webp', NULL, 'multinational', 16, true),
('CMIT', '/images/clients/cmit.png', NULL, 'construction', 17, true),
('Vina Glass', '/images/clients/vinaglass.png', NULL, 'construction', 18, true),
('NEC/Tokin', '/images/clients/tokin.png', NULL, 'japanese', 19, true),
('Shimazu', '/images/clients/shimadzu-logo.png', NULL, 'japanese', 20, true),
('Lixil', '/images/clients/lixil.png', NULL, 'japanese', 21, true),
('Newhope', '/images/clients/newhope-vn.jpeg', NULL, 'multinational', 22, true),
('Vina Koyei', '/images/clients/vina-kyoki.jpg', NULL, 'construction', 23, true)
ON CONFLICT DO NOTHING;
